import type { ControlCenterData } from "./types";

const now = "2026-06-28T08:45:00.000Z";

export const seedData: ControlCenterData = {
  projects: [
    {
      id: "project-wildsaura",
      name: "Wildsaura",
      description: "Creator/business workspace for wildlife content operations.",
      status: "active",
      created_at: now,
      updated_at: now,
    },
  ],
  project_memory: {
    "project-wildsaura": {
      id: "memory-wildsaura",
      project_id: "project-wildsaura",
      brand_tone: "Nature documentary",
      target_channels: ["Instagram", "TikTok"],
      posting_style: "Macro wildlife",
      hashtag_style: "Medium competition",
      notes: "Keep captions observant, specific, and calm.",
      updated_at: now,
    },
  },
  rules: [
    {
      id: "rule-draft-allowed",
      name: "Create Draft",
      action: "draft_content",
      effect: "allow",
      enabled: true,
    },
    {
      id: "rule-publish-review",
      name: "Publish Content",
      action: "publish_content",
      effect: "review",
      enabled: true,
    },
    {
      id: "rule-update-live-review",
      name: "Update Live Content",
      action: "update_live_content",
      effect: "review",
      enabled: true,
    },
    {
      id: "rule-delete-blocked",
      name: "Delete Resource",
      action: "delete_resource",
      effect: "block",
      enabled: true,
    },
    {
      id: "rule-comment-reply-review",
      name: "Reply Comment",
      action: "reply_comment",
      effect: "review",
      enabled: true,
    },
  ],
  tasks: [
    {
      id: "task-instagram-macro",
      project_id: "project-wildsaura",
      title: "Instagram macro insect post",
      goal: "Instagram macro insect post banana with caption and hashtags.",
      priority: "high",
      status: "queued",
      created_at: now,
      updated_at: now,
    },
  ],
  task_states: {
    "task-instagram-macro": {
      id: "state-instagram-macro",
      task_id: "task-instagram-macro",
      goal: "Instagram macro insect post banana with caption and hashtags.",
      current_stage: "Task captured, waiting for first AI pass",
      completed_steps: ["project selected", "goal saved"],
      next_step: "draft caption with AI-1",
      last_ai: "Unassigned",
      status: "queued",
      needs_review: false,
      metadata: {
        channel: "instagram",
        brand: "Wildsaura",
      },
      updated_at: now,
    },
  },
  ai_runs: [],
  handoff_summaries: [],
  action_logs: [
    {
      id: "log-seed-task-created",
      project_id: "project-wildsaura",
      task_id: "task-instagram-macro",
      actor: "User",
      action: "task.created",
      details: "Created task and initial state for Instagram macro insect post.",
      created_at: now,
    },
  ],
  approvals: [],
  connectors: [],
  website_control_map: [
    {
      id: "control-photos",
      project_id: "project-wildsaura",
      collection_name: "photos",
      display_name: "Photos",
      create_action: "addPhotoToFirestore",
      update_action: "updatePhotoInFirestore",
      delete_action: "deletePhotoFromFirestore",
      publish_behavior: "Create writes live Wildsaura photos with status approved, isPublic true, and published true.",
      source_file: "work/wildsaura/src/services/photoService.ts",
      source_function: "addPhotoToFirestore / updatePhotoInFirestore / deletePhotoFromFirestore",
      status: "review_required",
      action_statuses: { create: "review_required", update: "review_required", delete: "blocked", publish: "review_required" },
      metadata: { source: "wildsaura_audit", writes_enabled: false },
      created_at: now,
      updated_at: now,
    },
    {
      id: "control-stories",
      project_id: "project-wildsaura",
      collection_name: "stories",
      display_name: "Stories",
      create_action: "addStoryToFirestore",
      update_action: "updateStoryInFirestore",
      delete_action: "deleteStoryFromFirestore",
      publish_behavior: "Stories become visible through the live stories subscription after create.",
      source_file: "work/wildsaura/src/services/storyService.ts",
      source_function: "addStoryToFirestore / updateStoryInFirestore / deleteStoryFromFirestore",
      status: "review_required",
      action_statuses: { create: "review_required", update: "review_required", delete: "blocked", publish: "review_required" },
      metadata: { source: "wildsaura_audit", writes_enabled: false },
      created_at: now,
      updated_at: now,
    },
    {
      id: "control-videos",
      project_id: "project-wildsaura",
      collection_name: "videos",
      display_name: "Videos",
      create_action: "addVideoToFirestore",
      update_action: "updateVideoInFirestore",
      delete_action: "deleteVideoFromFirestore",
      publish_behavior: "Videos become visible through the live videos subscription after create.",
      source_file: "work/wildsaura/src/services/videoService.ts",
      source_function: "addVideoToFirestore / updateVideoInFirestore / deleteVideoFromFirestore",
      status: "review_required",
      action_statuses: { create: "review_required", update: "review_required", delete: "blocked", publish: "review_required" },
      metadata: { source: "wildsaura_audit", writes_enabled: false },
      created_at: now,
      updated_at: now,
    },
    {
      id: "control-comments",
      project_id: "project-wildsaura",
      collection_name: "comments",
      display_name: "Comments",
      create_action: "addCommentToFirestore",
      update_action: "not implemented",
      delete_action: "deleteCommentFromFirestore",
      publish_behavior: "Inbound photo, story, and video comments are captured into AI Control Center; AI replies require review.",
      source_file: "work/wildsaura/src/services/commentService.ts",
      source_function: "addCommentToFirestore / deleteCommentFromFirestore / sendToAiControlCenter",
      status: "available",
      action_statuses: { create: "available", update: "blocked", delete: "blocked", publish: "review_required", reply: "review_required" },
      metadata: { source: "wildsaura_audit", writes_enabled: false },
      created_at: now,
      updated_at: now,
    },
    {
      id: "control-community-posts",
      project_id: "project-wildsaura",
      collection_name: "community_posts",
      display_name: "Community Posts",
      create_action: "handleSubmitPost",
      update_action: "handleEditPost",
      delete_action: "handleDeletePost",
      publish_behavior: "Community posts and comments are live after authenticated Firestore writes; comment replies require review.",
      source_file: "work/wildsaura/src/components/CommunityPage.tsx",
      source_function: "handleSubmitPost / handleEditPost / handleDeletePost / handleComment",
      status: "review_required",
      action_statuses: { create: "review_required", update: "review_required", delete: "blocked", publish: "review_required", reply: "review_required" },
      metadata: { source: "wildsaura_audit", writes_enabled: false },
      created_at: now,
      updated_at: now,
    },
  ],
  messages: [],
  content_items: [],
  content_routes: [],
  content_schedule: [],
  publish_logs: [],
  media_assets: [],
  automation_rules: [],
};
